version: '3.8'

services:
  titanic-app:
    build: .
    ports:
      - "8080:8080"  # Map container's port 8080 to host's port 8080
    container_name: titanic_prediction_container
    restart: always
